repos:

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.1
    hooks:
      -   id: flake8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black